server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/registrosdb  # URL de conexión R2DBC
    username: postgres  # Usuario de la base de datos
    password: admin
  sql:
    init:
      mode: never
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
